{{- /* Airflow version 2.6.0 is when triggerer logs serve introduced */ -}}
{{- if semverCompare ">=2.6.0" .Values.airflowVersion }}
{{- if .Values.triggerer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}-triggerer
  labels:
    tier: airflow
    component: triggerer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- if or (.Values.labels) (.Values.triggerer.labels) }}
      {{- mustMerge .Values.triggerer.labels .Values.labels | toYaml | nindent 4 }}
    {{- end }}
spec:
  clusterIP: None
  selector:
    tier: airflow
    component: triggerer
    release: {{ .Release.Name }}
  ports:
    - name: triggerer-logs
      protocol: TCP
      port: {{ .Values.ports.triggererLogs }}
      targetPort: {{ .Values.ports.triggererLogs }}
{{- end }}
{{- end }}
